# Generated by Django 6.0 on 2025-12-26 05:43

import django.db.models.deletion
from django.db import migrations, models

def add_company_id_idempotent(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check for column
        cursor.execute("SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'employees_employee' AND column_name = 'company_id' AND table_schema = DATABASE()")
        if cursor.fetchone()[0] == 0:
            cursor.execute("ALTER TABLE employees_employee ADD COLUMN company_id bigint unsigned NULL")
        
        # Check for constraint
        cursor.execute("SELECT COUNT(*) FROM information_schema.table_constraints WHERE table_name = 'employees_employee' AND constraint_name = 'employees_employee_company_id_fk' AND table_schema = DATABASE()")
        if cursor.fetchone()[0] == 0:
            cursor.execute("ALTER TABLE employees_employee ADD CONSTRAINT employees_employee_company_id_fk FOREIGN KEY (company_id) REFERENCES organizations_company(id)")

        # Check for index
        cursor.execute("SELECT COUNT(*) FROM information_schema.statistics WHERE table_name = 'employees_employee' AND index_name = 'employees_employee_company_id_idx' AND table_schema = DATABASE()")
        if cursor.fetchone()[0] == 0:
            cursor.execute("CREATE INDEX employees_employee_company_id_idx ON employees_employee(company_id)")

def remove_company_id_idempotent(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE employees_employee DROP FOREIGN KEY IF EXISTS employees_employee_company_id_fk")
        cursor.execute("DROP INDEX IF EXISTS employees_employee_company_id_idx ON employees_employee")
        cursor.execute("ALTER TABLE employees_employee DROP COLUMN IF EXISTS company_id")


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_slack_user_id'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_company_id_idempotent, remove_company_id_idempotent),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='employee',
                    name='company',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.company'),
                ),
            ]
        ),
    ]
