# Generated by Django 5.2.9 on 2026-01-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='assigned_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='returned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Admin who received the returned device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_returns_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
