# Generated by Django 6.0 on 2025-12-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        # Manually add the column first to be safe for TiDB
        migrations.RunSQL(
            sql="ALTER TABLE departments_department ADD COLUMN manager_id bigint unsigned NULL",
            reverse_sql="ALTER TABLE departments_department DROP COLUMN manager_id"
        ),
        # Update Django state without running the DB-level AddField (which would fail)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='department',
                    name='manager',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
                ),
            ]
        ),
        # Manually add the constraint afterwards
        migrations.RunSQL(
            sql="ALTER TABLE departments_department ADD CONSTRAINT departments_department_manager_id_fk FOREIGN KEY (manager_id) REFERENCES employees_employee(id)",
            reverse_sql="ALTER TABLE departments_department DROP FOREIGN KEY departments_department_manager_id_fk"
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='departments.department'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_33d25b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='departments_code_35a421_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['department', 'level'], name='departments_departm_aea34c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('name', 'department')},
        ),
    ]
