# Generated by Django 5.2.9 on 2025-12-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__employe_08d913_idx',
            old_name='attendance_employee_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__date_61f2e1_idx',
            old_name='attendance_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__day_typ_d78ccf_idx',
            old_name='attendance_day_type_idx',
        ),
    ]
