# Generated by Django 5.2.9 on 2025-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day_type',
            field=models.CharField(choices=[('WORKING_DAY', 'Working Day'), ('HALF_DAY', 'Half Day'), ('LEAVE_DAY', 'Leave Day'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], default='WORKING_DAY', help_text='Type of day', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='orignal_total_time',
            field=models.IntegerField(default=32400, help_text='Scheduled total time in seconds (default from settings)'),
        ),
    ]
